#! /bin/bash


# Autostart
pkill picom
pkill sxhkd
pkill pulseaudio
#pkill batterywarn
sleep 0.1

feh --bg-fill ~/Wallpapers/tea.jpg

xrdb ~/xrdb/tea/tea &
picom --config /home/kira/.config/picom/picom.conf --experimental-backends &
/usr/bin/pulseaudio --start --log-target=syslog &

/usr/bin/xdg-user-dirs-update

/usr/libexec/polkit-gnome-authentication-agent-1 & eval $(gnome-keyring-daemon -s --components=pkcs11,secrets,ssh,gpg) &
sh /home/kira/.config/polybar/launch.sh &
setxkbmap -model pc105 -layout us -option grp:alt_shift_toggle &
sxhkd &
#xautolock -time 10 -locker "~/scripts/lock.sh" &
xsetroot -cursor_name left_ptr &



# Workspaces

bspc monitor -d 一 二 三 四 五 六 七 八 other 

# Source the colors

# source "${HOME}/.cache/wal/colors.sh"
. "${HOME}/.config/colors.sh"


# Set the border colors

bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"


# Use the line below if you are on bspwm >= 0.9.4

#bspc config presel_feedback_color "$color1"
bspc config presel_border_color "$color1"


# Borders and Gaps
bspc config border_radius       0
bspc config border_width         3.5
bspc config window_gap          15

bspc config bottom_padding 25
bspc config top_padding 10

bspc config split_ratio          0.50
#bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config click_to_focus       true


# Rules

bspc config external_rules_command "$(which /home/kira/.config/bspwm/bspwm-rules)"

bspc rule -a discord desktop="other" state=tiled follow=off
bspc rule -a origin.exe state=floating 

bspc rule -a Sxiv state=floating
bspc rule -a feh state=floating


pkill dunst
pkill ckb-next
sleep 0.1
ckb-next --background &
dunst -conf ~/.config/dunst/dunstrc &
