# Shell variables
# Generated by 'wal'
wallpaper='/home/kira/Wallpapers/tea.jpg'

# Special
background='#0B0112'
foreground='#ecdfe1'
cursor='#ecdfe1'

# Colors
color0='#0B0112'
color1='#676E88'
color2='#7C7F89'
color3='#877A86'
color4='#A19DA6'
color5='#C2B9C2'
color6='#D9D3D7'
color7='#ecdfe1'
color8='#a59c9d'
color9='#676E88'
color10='#7C7F89'
color11='#877A86'
color12='#A19DA6'
color13='#C2B9C2'
color14='#D9D3D7'
color15='#ecdfe1'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"